import { Product } from "./models/productModel";

export const ProductList: Product[] = [
  {
    name: "Hammer",
    slug: "hammer",
    image: "./Images/hammer.jpg",
    category: "Hand Tools",
    brand: "ABC Tools",
    price: 15.99,
    countInStock: 0,
    description: "A durable hammer for construction and woodworking tasks.",
  },
  {
    name: "Screwdriver Set",
    slug: "screwdriver-set",
    image: "./Images/screwdriver-set.jpg",
    category: "Hand Tools",
    brand: "XYZ Tools",
    price: 24.99,
    countInStock: 30,
    description: "A set of screwdrivers with various sizes and types for versatile use.",
  },
  {
    name: "Circular Saw",
    slug: "circular-saw",
    image: "./Images/circular-saw.jpg",
    category: "Power Tools",
    brand: "DefTech",
    price: 129.99,
    countInStock: 10,
    description: "A powerful circular saw for precise cutting in construction projects.",
  },
  {
    name: "Paint Roller",
    slug: "paint-roller",
    image: "./Images/paint-roller.jpg",
    category: "Painting Supplies",
    brand: "Hippo Acrylon",
    price: 9.99,
    countInStock: 100,
    description: "A high-quality paint roller for smooth and even paint application.",
  },
  {
    name: "Safety Helmet",
    slug: "safety-helmet",
    image: "./Images/safety-helmet.jpg",
    category: "Safety Equipment",
    brand: "Protecto",
    price: 19.99,
    countInStock: 20,
    description: "A durable safety helmet for protection on construction sites.",
  },
  {
    name: "Measuring Tape",
    slug: "measuring-tape",
    image: "./Images/measuring-tape.jpg",
    category: "Measuring Tools",
    brand: "AccuMeasure",
    price: 8.99,
    countInStock: 60,
    description: "A flexible measuring tape with metric and imperial units.",
  },
  {
    name: "Drill Bit Set",
    slug: "drill-bit-set",
    image: "./Images/drill-bit-set.jpg",
    category: "Drilling Accessories",
    brand: "ProDrill",
    price: 29.99,
    countInStock: 15,
    description: "A comprehensive set of drill bits for various drilling applications.",
  },
  {
    name: "Pliers",
    slug: "pliers",
    image: "./Images/pliers.jpg",
    category: "Hand Tools",
    brand: "GripMaster",
    price: 12.99,
    countInStock: 40,
    description: "A versatile pair of pliers for gripping, bending, and cutting wires.",
  },
  {
    name: "Cordless Drill",
    slug: "cordless-drill",
    image: "./Images/cordless-drill.jpg",
    category: "Power Tools",
    brand: "PowerPro",
    price: 79.99,
    countInStock: 5,
    description: "A cordless drill with adjustable torque settings for drilling and screwdriving tasks.",
  },
  {
    name: "Work Gloves",
    slug: "work-gloves",
    image: "./Images/work-gloves.jpg",
    category: "Safety Equipment",
    brand: "SafeHands",
    price: 7.99,
    countInStock: 80,
    description: "Protective work gloves with excellent grip and comfort.",
  },
  // New Products
  {
    name: "Wrench Set",
    slug: "wrench-set",
    image: "./Images/wrench-set.jpg",
    category: "Hand Tools",
    brand: "SuperFix",
    price: 29.99,
    countInStock: 25,
    description: "A versatile set of wrenches for various mechanical and plumbing tasks.",
  },
  {
    name: "Hacksaw",
    slug: "hacksaw",
    image: "./Images/hacksaw.jpg",
    category: "Hand Tools",
    brand: "CutPro",
    price: 18.99,
    countInStock: 15,
    description: "A durable hacksaw for cutting metal, plastic, and other materials.",
  },
  {
    name: "Power Drill",
    slug: "power-drill",
    image: "./Images/power-drill.jpg",
    category: "Power Tools",
    brand: "Fixman Tools",
    price: 89.99,
    countInStock: 8,
    description: "A powerful electric drill for heavy-duty drilling and driving tasks.",
  },
  {
    name: "Paintbrush Set",
    slug: "paintbrush-set",
    image: "./Images/paintbrush-set.jpg",
    category: "Painting Supplies",
    brand: "ArtMaster",
    price: 12.99,
    countInStock: 60,
    description: "A set of high-quality paintbrushes for smooth and precise paint application.",
  },
  {
    name: "Safety Goggles",
    slug: "safety-goggles",
    image: "./Images/safety-goggles.jpg",
    category: "Safety Equipment",
    brand: "GIGATOOLS",
    price: 8.99,
    countInStock: 30,
    description: "Protective goggles with clear lenses for eye protection in hazardous environments.",
  },
  {
    name: "Level Tool",
    slug: "level-tool",
    image: "./Images/level-tool.jpg",
    category: "Measuring Tools",
    brand: "AccuLevel",
    price: 16.99,
    countInStock: 20,
    description: "A reliable level tool for ensuring straight and accurate measurements.",
  },
  {
    name: "Drill Press",
    slug: "drill-press",
    image: "./Images/drill-press.jpg",
    category: "Drilling Accessories",
    brand: "Central Machinery",
    price: 249.99,
    countInStock: 3,
    description: "A stationary drill press for precise drilling in woodworking and metalworking.",
  },
  {
    name: "Wire Cutter",
    slug: "wire-cutter",
    image: "./Images/wire-cutter.jpg",
    category: "Hand Tools",
    brand: "Beadthoven",
    price: 9.99,
    countInStock: 35,
    description: "A sharp wire cutter for cutting and stripping electrical wires.",
  },
  {
    name: "Jigsaw",
    slug: "jigsaw",
    image: "./Images/jigsaw.jpg",
    category: "Power Tools",
    brand: "CRAFTSMAN",
    price: 109.99,
    countInStock: 6,
    description: "A versatile jigsaw for cutting intricate curves and shapes in wood and other materials.",
  },
  {
    name: "Face Shield",
    slug: "face-shield",
    image: "./Images/face-shield.jpg",
    category: "Safety Equipment",
    brand: "ClearVisor",
    price: 12.99,
    countInStock: 25,
    description: "A transparent face shield for full-face protection against splashes, impacts, and debris.",
  },
  {
    name: "Angle Finder",
    slug: "angle-finder",
    image: "./Images/angle-finder.jpg",
    category: "Measuring Tools",
    brand: "Dolity",
    price: 14.99,
    countInStock: 15,
    description: "A handy tool for measuring and transferring angles accurately.",
  },


]